### ISSUE TITLE
Get latest stable browsers function throws an exception

### ISSUE THREAD

**Issue by Mogztter** [Nyalab/caniuse-api#74]
```js
const caniuse = require('caniuse-api')
caniuse.getLatestStableBrowsers();
```
```
TypeError: Cannot read property 'lastVersions' of undefined
    at Object.getLatestStableBrowsers (node_modules/caniuse-api/dist/index.js:85:41)
    at Context.<anonymous> (test/test.js:14:13)
```

```
caniuse-lite: "1.0.30000830"
caniuse-api: "2.0.0"
browserslist: "2.11.3"
```

**Comment by Mogztter** [comment]
Looks like this issue was fixed in https://github.com/Nyalab/caniuse-api/pull/71
Do you plan to release a new version soon ?

**Comment by Nyalab** [comment]
Yes very soon, i just had a baby, time to get back on it, and i'll ship a new version.

**Comment by Mogztter** [comment]
Oh congratulations! No rush, enjoy 😄
